const isSS = document.body.clientWidth < 720;
const products = [
  {
    key: 'verygood2018',
    name: 'V利购德',
    desc: '东莞首家无人售卖商城',
    img: require('./product/verygood2018.png'),
    website: isSS ? 'http://m.nssi.jsontec.com' : 'http://www.vligoude.com',
    display: [
      require('./display/verygood2018/FireShotCapture42.png'),
      require('./display/verygood2018/FireShotCapture43.png'),
      require('./display/verygood2018/FireShotCapture44.png'),
      require('./display/verygood2018/FireShotCapture45.png'),
      require('./display/verygood2018/FireShotCapture46.png'),
      require('./display/verygood2018/FireShotCapture47.png'),
      require('./display/verygood2018/FireShotCapture48.png'),
      require('./display/verygood2018/FireShotCapture49.png'),
    ],
  },
  {
    key: 'zaobangshou',
    name: '藻帮手',
    desc: '藻帮手商城',
    img: require('./product/zaobangshou.png'),
    website: isSS ? 'http://app.zaobangshou.com/android.html#/' : 'http://www.lvanqi.com',
    display: [
      require('./display/zaobangshou/FireShotCapture1.png'),
      require('./display/zaobangshou/FireShotCapture2.png'),
      require('./display/zaobangshou/FireShotCapture3.png'),
    ],
  },
  {
    key: 'football',
    name: '贝利足球',
    desc: '东莞业余爱好者平台',
    img: require('./product/football.png'),
    website: isSS ? null : 'https://pro.modao.cc/app/DXWOPQeCfTSQNBVyAksTN1KZkf70IkQ',
    display: [
      require('./display/football/FireShotCapture35.png'),
      require('./display/football/FireShotCapture36.png'),
      require('./display/football/FireShotCapture37.png'),
      require('./display/football/FireShotCapture38.png'),
      require('./display/football/FireShotCapture39.png'),
      require('./display/football/FireShotCapture40.png'),
    ],
  },
  {
    key: 'dgmsa',
    name: '东莞海事局',
    desc: '起航,政务也走进互联网',
    img: require('./product/dgmsa.png'),
    website: isSS ? null : 'http://dghsj.jsontec.com',
    access: 'private',
    width: '1400px',
    display: [
      require('./display/dgmsa/FireShotCapture50.png'),
      require('./display/dgmsa/FireShotCapture51.png'),
      require('./display/dgmsa/FireShotCapture52.png'),
      require('./display/dgmsa/FireShotCapture53.png'),
    ],
  },
  {
    key: 'zhiteyou',
    name: '智特优',
    desc: '买奶粉，信得过',
    img: require('./product/zhiteyou.png'),
    website: isSS ? 'http://ds-partner.jsontec.com' : 'http://ds-partner.jsontec.com',
    display: [
      require('./display/zhiteyou/FireShotCapture1.jpg'),
      require('./display/zhiteyou/FireShotCapture2.png'),
    ],
  },
  {
    key: 'bajiaer',
    name: '8+2',
    desc: '8种技巧+2种机遇',
    img: require('./product/bajiaer.png'),
    website: isSS ? 'http://ds-partner2.jsontec.com' : 'http://ds-partner2.jsontec.com',
    display: [
      require('./display/bajiaer/snipaste_20180904_173328.png'),
      require('./display/bajiaer/snipaste_20180904_173349.png'),
    ],
  },
  {
    key: 'jutianwu',
    name: '居田屋',
    desc: '吃寿司！来居田屋',
    img: require('./product/jutianwu.png'),
    website: isSS ? 'http://jxjtw.jsontec.com/mobile' : 'http://jxjtw.jsontec.com',
    display: [
      require('./display/jutianwu/FireShotCapture55.png'),
      require('./display/jutianwu/FireShotCapture56.png'),
      require('./display/jutianwu/FireShotCapture57.png'),
      require('./display/jutianwu/FireShotCapture58.png'),
      require('./display/jutianwu/FireShotCapture60.png'),
    ],
  },
  {
    key: 'yijinrong',
    name: '山西乂科技',
    desc: '乂金融,引领科技潮流',
    img: require('./product/yijinrong.png'),
    website: isSS ? 'http://a.app.qq.com/o/simple.jsp?pkgname=com.jsontec.crowd_funding' : 'http://yijinrong.jsontec.com',
    display: [
      require('./display/yijinrong/FireShotCapture1.jpg'),
      require('./display/yijinrong/FireShotCapture2.jpg'),
      require('./display/yijinrong/FireShotCapture3.jpg'),
      require('./display/yijinrong/FireShotCapture4.jpg'),
      require('./display/yijinrong/FireShotCapture5.jpg'),
    ],
  },
  {
    key: 'shengxianb2b',
    name: '景泰地产生鲜B2B',
    desc: 'B2B平台经营生鲜蔬果',
    img: require('./product/shengxianb2b.png'),
    website: isSS ? 'http://sxb2b.jsontec.com' : 'http://sxb2b.jsontec.com',
    display: [
      require('./display/shengxianb2b/FireShotCapture61.png'),
      require('./display/shengxianb2b/FireShotCapture62.png'),
      require('./display/shengxianb2b/FireShotCapture63.png'),
    ],
  },
  {
    key: 'jxshop',
    name: '积信微商',
    desc: '快速建站抓住商机',
    img: require('./product/jxshop.png'),
    website: isSS ? 'http://jxds.jsontec.com/mobile' : 'http://jxds.jsontec.com',
    display: [
      require('./display/jxshop/FireShotCapture64.png'),
      require('./display/jxshop/FireShotCapture65.png'),
      require('./display/jxshop/FireShotCapture67.png'),
    ],
  },
  {
    key: 'dbd',
    name: '多宝贷',
    desc: '广东莞贷互联网信息服务',
    img: require('./product/dbd.png'),
    website: isSS ? 'http://a.app.qq.com/o/simple.jsp?pkgname=com.showsoft.duobaodai' : 'http://a.app.qq.com/o/simple.jsp?pkgname=com.showsoft.duobaodai',
    display: [
      require('./display/dbd/x1.jpg'),
      require('./display/dbd/x2.jpg'),
      require('./display/dbd/x3.jpg'),
      require('./display/dbd/x4.jpg'),
    ],
  },
  {
    key: 'd3manage',
    name: 'D3管家',
    desc: '价值几何 尽在掌握',
    img: require('./product/d3manage.png'),
    website: isSS ? 'http://a.app.qq.com/o/simple.jsp?pkgname=jsontec.dgutwindy.jsontec_D3' : 'http://www.imxiaochengxu.com/minapp/1003798',
    display: [
      require('./display/d3manage/149959036658877586.png'),
      require('./display/d3manage/149959036737743870.jpg'),
      require('./display/d3manage/149959036757639761.jpg'),
      require('./display/d3manage/149959036872296214.jpg'),
      require('./display/d3manage/149959036896193474.jpg'),
    ],
  },
  {
    key: 'piaolide',
    name: '票立得',
    desc: '开发票就是容易',
    img: require('./product/piaolide.png'),
    website: isSS ? 'http://pld.bonsaii.com/mobile' : 'http://pld.bonsaii.com',
    width: '650px',
    display: [
      require('./display/piaolide/Comp1_00000.jpg'),
      require('./display/piaolide/Comp2_00000.jpg'),
      require('./display/piaolide/Comp3_00000.jpg'),
    ],
  },
  {
    key: 'yugongwang',
    name: '愚工网',
    desc: '通信工程',
    img: require('./product/yugongwang.png'),
    website: isSS ? 'http://www.elitept.cn/mobile/index/app' : 'http://www.elitept.cn',
    display: [
      require('./display/yugongwang/FireShotCapture1.png'),
      require('./display/yugongwang/FireShotCapture2.png'),
      require('./display/yugongwang/FireShotCapture3.png'),
      require('./display/yugongwang/FireShotCapture4.png'),
    ],
  },
  {
    key: 'haisihui',
    name: '海丝汇',
    desc: '东莞海丝汇进出口',
    img: require('./product/haisihui.png'),
    website: isSS ? 'http://hsh.jsontec.com' : null,
    display: [
      require('./display/haisihui/FireShotCapture68.png'),
      require('./display/haisihui/FireShotCapture70.jpg'),
      require('./display/haisihui/FireShotCapture71.png'),
      require('./display/haisihui/FireShotCapture72.png'),
      require('./display/haisihui/FireShotCapture73.png'),
    ],
  },
  {
    key: 'zhangfangbao',
    name: '掌房宝',
    desc: '轻松愉快买房',
    img: require('./product/zhangfangbao.png'),
    website: isSS ? 'https://itunes.apple.com/CN/app/id1159257845' : 'https://itunes.apple.com/CN/app/id1159257845',
    display: [
      require('./display/zhangfangbao/FireShotCapture1.jpg'),
      require('./display/zhangfangbao/FireShotCapture2.jpg'),
      require('./display/zhangfangbao/FireShotCapture3.jpg'),
      require('./display/zhangfangbao/FireShotCapture4.jpg'),
      require('./display/zhangfangbao/FireShotCapture5.jpg'),
    ],
  },
  {
    key: 'govshipai',
    name: '石排',
    desc: '互联网政务示例',
    img: require('./product/govshipai.png'),
    website: isSS ? 'http://gov-shipai.jsontec.cn:81' : null,
    display: [
      require('./display/govshipai/20161018113229.jpg'),
      require('./display/govshipai/20161018113252.jpg'),
      require('./display/govshipai/20161018113309.jpg'),
      require('./display/govshipai/20161018113354.jpg'),
    ],
  },
  {
    key: 'pingandongguan',
    name: '平安东莞',
    desc: '互联网政务示例',
    img: require('./product/pingandongguan.png'),
    website: isSS ? 'http://padg.jsontec.com' : 'http://padg.jsontec.com',
    display: [
      require('./display/pingandongguan/FireShotCapture82.png'),
      require('./display/pingandongguan/FireShotCapture83.png'),
      require('./display/pingandongguan/FireShotCapture84.png'),
      require('./display/pingandongguan/FireShotCapture85.png'),
    ],
  },
  {
    key: 'pinganliaobu',
    name: '平安寮步',
    desc: '互联网政务示例',
    img: require('./product/pinganliaobu.png'),
    website: isSS ? 'http://pinganliaobu.jsontec.cn:81' : 'http://pinganliaobu.jsontec.cn:81',
    display: [
      require('./display/pinganliaobu/FireShotCapture86.png'),
      require('./display/pinganliaobu/FireShotCapture87.png'),
      require('./display/pinganliaobu/FireShotCapture88.png'),
    ],
  },
  {
    key: 'ys',
    name: '积信商城',
    desc: '传统O2O电商',
    img: require('./product/ys.png'),
    website: isSS ? 'http://jxds.jsontec.com/mobile' : 'http://jxds.jsontec.com',
    display: [
      require('./display/ys/FireShotCapture1.png'),
      require('./display/ys/FireShotCapture2.png'),
      require('./display/ys/FireShotCapture3.png'),
      require('./display/ys/FireShotCapture4.png'),
    ],
  },
  {
    key: 'klc',
    name: '积信筹',
    desc: '社交与电商结合',
    img: require('./product/klc.png'),
    website: isSS ? 'http://klc.jsontec.com' : 'http://klc.jsontec.com',
    display: [
      require('./display/klc/klc04.png'),
      require('./display/klc/klc05.png'),
    ],
  },
  {
    key: 'dcxt',
    name: '酒店点餐',
    desc: '随时随地，想点就点',
    img: require('./product/dcxt.png'),
    website: isSS ? null : null,
  },
  {
    key: 'gradred',
    name: '积信抢红包',
    desc: '红包拿来，不用伸手',
    img: require('./product/gradred.png'),
    website: isSS ? 'http://fir.im/wxqhb' : 'http://fir.im/wxqhb',
    display: [
      require('./display/gradred/102_59c20f9edd55e867853855e3f5a8e1fd_234x360.jpg'),
      require('./display/gradred/102_573f1d18a09bf54cf1db2fe159afd4da_234x360.jpg'),
      require('./display/gradred/102_608c7324a711cd3e8a3c22b3074e4a79_234x360.jpg'),
      require('./display/gradred/102_1886d75bc4aac68e4cf73228617b16f6_234x360.jpg'),
    ],
  },
  {
    key: 'moa',
    name: '办公自动化',
    desc: '传统的OA作业移动版',
    img: require('./product/moa.png'),
    website: isSS ? 'http://moa.jsontec.com' : 'http://moa.jsontec.com',
    display: [
      require('./display/moa/FireShotCapture74.png'),
      require('./display/moa/FireShotCapture75.png'),
      require('./display/moa/FireShotCapture76.png'),
      require('./display/moa/FireShotCapture77.png'),
    ],
  },
  {
    key: 'erp',
    name: '进销存ERP',
    desc: '传统的erp系统',
    img: require('./product/erp.png'),
    website: isSS ? null : null,
  },
  {
    key: 'lzyp',
    name: '老曾优配',
    desc: '主营品牌汽车零件等',
    img: require('./product/laozengyoupei.png'),
    website: isSS ? 'http://lzyp.jsontec.com' : 'http://lzyp.jsontec.com',
    display: [
      require('./display/laozengyoupei/FireShotCapture89.png'),
      require('./display/laozengyoupei/FireShotCapture90.png'),
      require('./display/laozengyoupei/FireShotCapture91.png'),
      require('./display/laozengyoupei/FireShotCapture92.png'),
      require('./display/laozengyoupei/FireShotCapture93.png'),
    ],
  },
  {
    key: 'wxgames',
    name: '微信H5小游戏',
    desc: '新奇有趣，营销奇策',
    img: require('./product/wxgames.png'),
    website: isSS ? 'http://wxgames.jsontec.com' : 'http://wxgames.jsontec.com',
    display: [
      require('./display/wxgames/FireShotCapture1.png'),
      require('./display/wxgames/FireShotCapture2.png'),
      require('./display/wxgames/FireShotCapture3.png'),
      require('./display/wxgames/FireShotCapture4.png'),
    ],
  },
  {
    key: 'msb',
    name: '名师宝',
    desc: '教育之路，电商之路',
    img: require('./product/msb.png'),
    website: isSS ? 'http://msb365.cn.b2bhs.com' : 'http://msb365.cn.b2bhs.com',
    display: [
      require('./display/msb/170839_18450902.jpg'),
      require('./display/msb/20157114435118210.jpg'),
      require('./display/msb/20157114436774860.jpg'),
      require('./display/msb/201571134151986080.jpeg'),
    ],
  },
  {
    key: 'ecx',
    name: 'E出行',
    desc: 'E人出行，万车呼应',
    img: require('./product/ecx.png'),
    website: isSS ? 'https://www.vipcn.com/shoujiruanjian/bianjieshenghuo/330048.html' : 'https://www.vipcn.com/shoujiruanjian/bianjieshenghuo/330048.html',
    display: [
      require('./display/ecx/2016331134338118210.jpg'),
      require('./display/ecx/2016331134339653750.jpg'),
      require('./display/ecx/2016331134340219310.jpg'),
      require('./display/ecx/2016331134341219310.jpg'),
    ],
  },
  {
    key: 'blood',
    name: 'YDATA创库',
    desc: '健康智能血糖仪',
    img: require('./product/blood.png'),
    website: isSS ? 'https://www.wandoujia.com/apps/com.easyder.glucosemeter' : 'https://www.wandoujia.com/apps/com.easyder.glucosemeter',
    display: [
      require('./display/blood/102_5fee17286396c46025429ab4a9889989_234x360.jpg'),
      require('./display/blood/102_2231c063f6f398d2e8f6f270edfe9316_234x360.jpg'),
      require('./display/blood/102_edc8baa304caf8608adeb23bbddcce38_234x360.jpg'),
    ],
  },
];
export default products;
